### ISSUE TITLE
Function in callback

### ISSUE THREAD

**Issue by pBauma** [VaclavSynacek/RF24SN_nodejs_Server#3]
A Javascript string is not accepted as an argument in setTimeout.

~~~~
timers.js:327
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:327:11)
    at processPublishPacket (/usr/local/lib/node_modules/rf24sn/index.js:104:3)
    at PRX.<anonymous> (/usr/local/lib/node_modules/rf24sn/index.js:88:31)
    at emitOne (events.js:96:13)
    at PRX.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at PRX.Readable.push (_stream_readable.js:134:10)
    at PRX.<anonymous> (/usr/local/lib/node_modules/rf24sn/node_modules/nrf/index.js:584:41)
    at /usr/local/lib/node_modules/rf24sn/node_modules/nrf/index.js:317:17
    at _finish (/usr/local/lib/node_modules/rf24sn/node_modules/fifolock/index.js:31:13)
~~~~

**Comment by pBauma** [comment]
Solve by wrapping the function call in 

```javascript
function (){sendPacket(packet)}
```

**Comment by ArJay60** [comment]
timers.js:427
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at setTimeout (timers.js:427:11)
    at processPublishPacket (/usr/lib/node_modules/rf24sn/index.js:104:3)
    at PRX.<anonymous> (/usr/lib/node_modules/rf24sn/index.js:88:31)
    at emitOne (events.js:116:13)
    at PRX.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PRX.Readable.push (_stream_readable.js:208:10)
    at PRX.<anonymous> (/usr/lib/node_modules/rf24sn/node_modules/nrf/index.js:584:41)
    at /usr/lib/node_modules/rf24sn/node_modules/nrf/index.js:317:17

But function seems to be wrapped -->
 setTimeout(function () {
                // HACK: chip seems to assert RX_DR a while before setting RX_P_NO, so poll if necessary
                // TODO: this may actually just happen until we reset RX_DR (maybe FLUSH_RX or similar unsyncs?)
                // see also note on top of datasheet p.52 about status register updated *during* IRQ transmission
                if (nrf._debug) console.warn("- weird status, checking again -");
                nrf._checkStatus(false);
            }, 0);

Help needed!

**Comment by VaclavSynacek** [comment]
Sorry, but I don't understand what you are trying to do. What is your hardware setup? What software do you use on nodes? What is the content of the whole packet that fails? Is it failing on the transmission from the node to mqtt or from mqtt to nodes? What is the output of this program if run with `-vvvv` argument?

I have no idea what this whole issue is about and just pasting an error message that had never happened in my setup without other context is not enough for me to understand the problem.

**Comment by ArJay60** [comment]
Ye, that is not that smart from me. Working with PI3 (v9 stretch) and a single Arduino (your client lib).  On PI3 nodejs v8.9.3,  Running rf24sn gives me:

debug: radio initialized
info: publish packet received { value: 10,
  sensorId: 7,
  nodeId: 99,
  reserved: 255,
  packetType: 1 }
silly: opening new TX pipe for new client 99
silly: replyPipes now contain [ <99 empty items>,
  PTX {
    _readableState:
     ReadableState {
       objectMode: false,
       highWaterMark: 64,
       buffer: [Object],
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: null,
       ended: false,
       endEmitted: false,
       reading: false,
       sync: true,
       needReadable: false,
       emittedReadable: false,
       readableListening: false,
       resumeScheduled: false,
       destroyed: false,
       defaultEncoding: 'utf8',
       awaitDrain: 0,
       readingMore: false,
       decoder: null,
       encoding: null },
    readable: true,
    domain: null,
    _events: { end: [Object], close: [Object] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState:
     WritableState {
       objectMode: false,
       highWaterMark: 64,
       finalCalled: false,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       destroyed: false,
       decodeStrings: true,
       defaultEncoding: 'utf8',
       length: 0,
       writing: false,
       corked: 0,
       sync: true,
       bufferProcessing: false,
       onwrite: [Function: bound onwrite],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false,
       bufferedRequestCount: 0,
       corkedRequestsFree: [Object] },
    writable: true,
    allowHalfOpen: true,
    opts: { size: 8, autoAck: false, ackPayloads: false, _enableRX: false },
    _pipe: 0,
    _addr: <Buffer f0 f0 f0 f0 63>,
    _size: 8,
    _wantsRead: false,
    _sendOpts: { ack: false } } ]
timers.js:427
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at setTimeout (timers.js:427:11)
    at processPublishPacket (/usr/lib/node_modules/rf24sn/index.js:104:3)
    at PRX.<anonymous> (/usr/lib/node_modules/rf24sn/index.js:88:31)
    at emitOne (events.js:116:13)
    at PRX.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PRX.Readable.push (_stream_readable.js:208:10)
    at PRX.<anonymous> (/usr/lib/node_modules/rf24sn/node_modules/nrf/index.js:5                                                                                                             84:41)
    at /usr/lib/node_modules/rf24sn/node_modules/nrf/index.js:317:17

**Comment by VaclavSynacek** [comment]
Unfortunatelly I don't have HW set up to test this.
Could you, @ArJay60 , please test [branch _fix #3_](/VaclavSynacek/RF24SN_nodejs_Server/tree/FIX_%233) ? Thank you.
I created that based on @pBauma 's fix above.

**Comment by ArJay60** [comment]
Hi Vaclav, With nodejs version 4.8.3. pre fix#3 and fix#3 are working fine. When upgrading nodejs to version  8.11.3 (due to installing node-red) I now get a error message as below. Any thoughts?

module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/rf24sn/node_modules/nrf/node_modules/pi-spi/build/Release/spi_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

**Comment by VaclavSynacek** [comment]
I guess you have to reinstall [nrf](https://www.npmjs.com/package/nrf), which is a dependency of rf24sn. Or maybe easier: uninstall the whole rf24sn and install it again. It will either work and nfr will be recompiled under newer nodejs, or it will fail with more descriptive message.

**Comment by ArJay60** [comment]
Hi. Fresh install of raspbian on PI3. Installed Node-red gives me nodejs version 8.11.3. installed nrf. cloned fix3 of rf24sn. started rf24sn.
Error when receiving package:

pi@raspberrypi:~/node_modules/rf24sn $ ./index.js -vvvv
debug: radio initialized
info: publish packet received { value: 2, sensorId: 7, nodeId: 99, reserved: 255, packetType: 1 }
silly: opening new TX pipe for new client 99
silly: replyPipes now contain [ <99 empty items>,
  PTX {
    _readableState:
     ReadableState {
       objectMode: false,
       highWaterMark: 64,
       buffer: [Object],
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: null,
       ended: false,
       endEmitted: false,
       reading: false,
       sync: true,
       needReadable: false,
       emittedReadable: false,
       readableListening: false,
       resumeScheduled: false,
       destroyed: false,
       defaultEncoding: 'utf8',
       awaitDrain: 0,
       readingMore: false,
       decoder: null,
       encoding: null },
    readable: true,
    domain: null,
    _events: { end: [Object], close: [Object] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _writableState:
     WritableState {
       objectMode: false,
       highWaterMark: 64,
       finalCalled: false,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       destroyed: false,
       decodeStrings: true,
       defaultEncoding: 'utf8',
       length: 0,
       writing: false,
       corked: 0,
       sync: true,
       bufferProcessing: false,
       onwrite: [Function: bound onwrite],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false,
       bufferedRequestCount: 0,
       corkedRequestsFree: [Object] },
    writable: true,
    allowHalfOpen: true,
    opts: { size: 8, autoAck: false, ackPayloads: false, _enableRX: false },
    _pipe: 0,
    _addr: <Buffer f0 f0 f0 f0 63>,
    _size: 8,
    _wantsRead: false,
    _sendOpts: { ack: false } } ]
timers.js:450
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at setTimeout (timers.js:450:11)
    at processPublishPacket (/home/pi/RF24SN_nodejs_Server/index.js:104:3)
    at PRX.<anonymous> (/home/pi/RF24SN_nodejs_Server/index.js:88:31)
    at emitOne (events.js:116:13)
    at PRX.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PRX.Readable.push (_stream_readable.js:208:10)
    at PRX.<anonymous> (/home/pi/node_modules/nrf/index.js:584:41)
    at /home/pi/node_modules/nrf/index.js:317:17

**Comment by VaclavSynacek** [comment]
I honestly don't have an idea. Perhaps try more milliseconds than 50. Or swap setTimout for setImmediate or process.nextTick. Or try replacing the lines with `setTimeout(sendPacket, 50, packet);` which is the other notation that should be supported by nodejs. In any case it should be easier for you to investigate with a working setup than me trying blind without the hardware. In any case, let me know what worked.

**Comment by VaclavSynacek** [comment]
I have slept on the problem and have a hypothesis.

Maybe I always operated in slower mode then @ArJay60 . I always set up the server, then powered up the clients. Or the clients were slow, only reporting once every few minutes. So when index.js is executed, all of it got interpreted before the first packet came in.

However if the the the clients are firing packets fast and even before the index.js is executed, then maybe it really might be trying to call sendPacket before it gets defined.

I reorganized the code within the file and committed to [branch FIX #3](https://github.com/VaclavSynacek/RF24SN_nodejs_Server/tree/FIX_%233) again. @ArJay60, please retest.

(Hind of lame. I has been some time since I did any usable javascript coding. Also the syntax evolved since so the style of this repo is way out of date.)

**Comment by ArJay60** [comment]
Working fine now with the latest changes in the code from you. No other changes made. 

Can you tell me what you've changed? Just wrapped the two function calls to  setTimeout that are now--> setTimeout(function (){sendPacket(packet)}, 50) ??

**Comment by VaclavSynacek** [comment]
Yes that and also reordered the source so that sendPacket function definiton is before the setTimeout that calls it. It seems quite obvious in retrospect, but I just never encounetered the race condition you discovered, because I always first started the server, waited, the sendPacket functions got loaded by nodejs and only then I powered up the arduinos with client code. So when first packet reached server, the sendPacket functions were already loaded by nodejs. In your case, you probably managed to send packets from the arduinos even before nodejs got to process the sendPacket function definition at the end of js file and therefore nodejs complained that sendPacket is not a function (yet).

Good catch, thanks for the testing.
